---
title: "Gender Dynamics in Horror 2"
author: "Soham De"
output: html_notebook
--- 

```{r}
library("tm")
library("SnowballC")
library("RColorBrewer")
library("syuzhet")
library("ggplot2")
library(tidytext)
library(dplyr)
library(tidyr)
library(scales)
library(ggthemes)
library(magrittr)
library(devtools)
library(stringr)
library(widyr)
library(fuzzyjoin)
library(readr)

```
```{r}
library("tm")
library("SnowballC")
library("RColorBrewer")
library("syuzhet")
library("ggplot2")
library(tidytext)
library(dplyr)
library(tidyr)
library(scales)
library(ggthemes)
library(magrittr)
library(devtools)
library(stringr)
library(widyr)
library(fuzzyjoin)
library(readr)

```


```{r}
library(janeaustenr)
stoker_corpus <- read_csv("canons/stoker.csv") %>% unnest_tokens(text, text, token="sentences") %>% select(-author)
shelley_corpus <- read_csv("canons/shelley.csv") %>% unnest_tokens(text, text, token="sentences") %>% select(-author)
lovecraft_corpus <- read_csv("canons/lovecraft.csv") %>% unnest_tokens(text, text, token="sentences") %>% select(-author)
stevenson_corpus <- read_csv("canons/stevenson.csv") %>% unnest_tokens(text, text, token="sentences") %>% select(-author)
test_corpus <- read_csv("test.csv") %>% unnest_tokens(text, text, token="sentences") %>% select(-author)
austen_corpus <- austen_books()
```

```{r}
## Pre-Processing for the Shelley Corpus

austen_section_words <- austen_corpus %>%
  filter(book == "Pride & Prejudice") %>%
  mutate(section = row_number() %/% 10) %>%
  filter(section > 0) %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word)

test_section_words <- test_corpus %>%
  filter(title == "Frankestein") %>%
  mutate(section = row_number() %/% 10) %>%
  filter(section > 0) %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word)

shelley_section_words <- shelley_corpus %>%
  mutate(section = row_number() %/% 10) %>%
  filter(section > 0) %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word)

```

```{r}
austen_section_words %>% 
  pairwise_count(word, section, sort = TRUE)

test_section_words %>% 
  pairwise_count(word, section, sort = TRUE)

shelley_section_words %>% 
  pairwise_count(word, section, sort = TRUE)

```
```{r}
austen_section_words %>% 
  pairwise_count(word, section, sort = TRUE) %>% 
  filter(item1 == "darcy")

shelley_section_words %>% 
  pairwise_count(word, section, sort = TRUE) %>% 
  filter(item1 == "miserable" | item1 == "death" | item1 == "cry")
```

```{r}
word_cors <- shelley_section_words %>% 
  add_count(word) %>% 
  filter(n >= 20) %>% 
  select(-n) %>%
  pairwise_cor(word, section, sort = TRUE)
```

```{r}
word_cors %>%
  filter(correlation > .25) %>%
  as_tbl_graph() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), repel = TRUE)
```

